---
title: "Gov 50 Final Project"
author: "Ethan Johnstone"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---

## Project thoughts

I am interested in exploring data on the 2016 presidential election. In particular I want to see if there is a correlation between campaign stops and the turnout of the election in the area.


## Proposal

Do campaign stops impact voter turnout in Presidential elections? In this study, I plan to examine the relationship between Donald Trump's 2016 campaign stops and voter turnout at the county level. I hypothesize that Donald Trump's campaign stops increased overall voter turnout compared to counties that he did not visit. It is widely held that Trump used large campaign stops to garner energy, funds, and turnout voters in rural counties in swing states such as Wisconsin, Michigan, and Pennsylvania. This study will evaluate if this theory can be substantiated with voter turnout data from the 2016 election. My sample is comprised of county level voter turnout data compiled by the MIT Election Lab. My unit of analyses is Trump camping stops. My explanatory variable of interest is whether Trump held a campaign stop in a county or not. The variable is coded =1 if he held a campaign stop and =0 if he did not. My outcome variable is the percent of eligible voters that cast votes. For instance if this variable was coded =56, then this would indicate that 56% of eligible voters voted in that county. If I observe higher voter turnout in counties that Trump held campaign stops in, the data would support my hypothesis. If voter turnout was unchanged or less in counties he held stops in, then the data would disprove my hypothesis.











```{r}
library(tidyverse)
library(readxl)
turnout <- read_xlsx("Data/Turnout_Data_2016.xlsx", sheet = "County VTO")
names(turnout)[1:2] <- c("countyname", "state")
```

